from django.urls import path
from . import views

urlpatterns = [
    path('index/',views.index,name='index'),
    path('About/',views.About,name='About'),
    path('service/',views.service,name='service'),
    path('navbar/',views.navbar,name='navbar'),
    path('traffic/',views.traffic,name='traffic'),
    path('contaner/',views.contaner,name='contaner'),
    path('contaner2/',views.contaner2,name='contaner2'),
    path('contact/',views.contact,name='contact'),
    path('footer/', views.footer, name='footer'),
    path('Attendance/', views.Attendance, name='Attendance'),
    path('base/', views.base, name='base'),
    path('Cabin/', views.Cabin, name='Cabin'),
    path('Complete_Security/', views.Complete_Security, name='Complete_Security'),
    path('cone/', views.cone, name='cone'),
    path('construction/', views.construction, name='construction'),
    path('Container_Houses/', views.Container_Houses, name='Container_Houses'),
    path('Energy/', views.Energy, name='Energy'),
    path('Executive_Office_Container/', views.Executive_Office_Container, name='Executive_Office_Container'),
    path('flatpack/', views.flatpack, name='flatpack'),
    path('Food_Hospitality/', views.Food_Hospitality, name='Food_Hospitality'),
    path('Hotel_Rooms/', views.Hotel_Rooms, name='Hotel_Rooms'),
    path('Luxury_Modular_Site_Offices/', views.Luxury_Modular_Site_Offices, name='Luxury_Modular_Site_Offices'),
    path('luxuryvilla/', views.luxuryvilla, name='luxuryvilla'),
    path('metal/', views.metal, name='metal'),
    path('Mobile_Hospitals/', views.Mobile_Hospitals, name='Mobile_Hospitals'),
    path('Mobile_Office/', views.Mobile_Office, name='Mobile_Office'),
    path('Modular_office/', views.Modular_Office, name='Modular_Office'),
    path('mojo/', views.mojo, name='mojo'),
    path('MS_Bunk_Bed_Container/', views.MS_Bunk_Bed_Container, name='MS_Bunk_Bed_Container'),
    path('MS_Crowd/', views.MS_Crowd, name='MS_Crowd'),
    path('MS_STOP/', views.MS_STOP, name='MS_STOP'),
    path('Municipal_Garbage/', views.Municipal_Garbage, name='Municipal_Garbage'),
    path('office_metal_container/', views.office_metal_container, name='office_metal_container'),
    path('office/', views.office, name='office'),
    path('office-and-home/', views.office_and_home, name='office_and_home'),
    path('oil/', views.oil, name='oil'),
    path('Plastic_Safety_Products/', views.Plastic_Safety_Products, name='Plastic_Safety_Products'),
    path('PlasticSpeedBreaker/', views.PlasticSpeedBreaker, name='PlasticSpeedBreaker'),
    path('Porta_Cabins/', views.Porta_Cabins, name='Porta_Cabins'),
    path('Portable_house/', views.Portable_house, name='Portable_house'),
    path('Portable_Gym/', views.Portable_Gym, name='Portable_Gym'),
    path('Portable_Security_Guard_Cabins/', views.Portable_Security_Guard_Cabins, name='Portable_Security_Guard_Cabins'),
    path('Portable_Toilet_Container/', views.Portable_Toilet_Container, name='Portable_Toilet_Container'),
    path('Reefer/', views.Reefer, name='Reefer'),
    path('Restaurant_Container/', views.Restaurant_Container, name='Restaurant_Container'),
    path('Rubber_Road_Signages/', views.Rubber_Road_Signages, name='Rubber_Road_Signages'),
    path('RubberSpeedBreaker/', views.RubberSpeedBreaker, name='RubberSpeedBreaker'),
    path('SandandWater/', views.SandandWater, name='SandandWater'),
    path('Sanitation_Hygiene_Solutions/', views.Sanitation_Hygiene_Solutions, name='Sanitation_Hygiene_Solutions'),
    path('single/', views.single, name='single'),
    path('SSQueueManager/', views.SSQueueManager, name='SSQueueManager'),
    path('Standard_Office/', views.Standard_Office, name='Standard_Office'),
    path('Swimming_Pool_Containers/', views.Swimming_Pool_Containers, name='Swimming_Pool_Containers'),
    path('Toilet_on_Construction_Site/', views.Toilet_on_Construction_Site, name='Toilet_on_Construction_Site'),
    path('Trafic_Mirrors/', views.Trafic_Mirrors, name='Trafic_Mirrors'),
    path('Wildlife/', views.Wildlife, name='Wildlife'),
    
    
    

]    
